config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'api/news'
  get 'api/:date1/:date2',    to: 'api#between_dates'
  resources :blogs
  get 'pages/index'
  get 'inicio/index'
  root 'inicio#index'

  # get 'edificios/index'
  get "edificios",       to: "edificios#index",   as: "list_edificios"
  get 'edificios/new',   to: "edificios#new",     as: "new_edificio"
  get "edificios/:id",   to: "edificios#show",     as: "edificio"
  get "edificios/:id/edit", to: "edificios#edit",  as: "edit_edificio"
  
  post "edificios",      to: "edificios#create"
  patch "edificios/:id", to: "edificios#update"
  put "edificios/:id",   to: "edificios#update" 
  delete "edificios/:id", to: "edificios#destroy",  as: "eliminar_edificio"   
  ###############################
  resources :departamentos
  #Por que agrega esto en la guía
  #################################
  get "clientes",          to: "clientes#index",   as: "clientes"
  get "clientes/new",      to: "clientes#new",     as: "new_cliente"
  get "clientes/:id",      to: "clientes#show",    as: "cliente"
  get "clientes/:id/edit", to: "clientes#edit",    as: "edit_cliente"

  post "clientes",         to: "clientes#create"
  patch "clientes/:id",     to: "clientes#update"
  put "clientes/:id",       to: "clientes#update"
  delete "clientes/:id",    to: "clientes#destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "pages/index",        to: "pages#index",      as: "pages"
  get "pages/create",       to: "pages#create",     as: "create_pages"
  get '/pages/dashboard',    to: "pages#dashboard",   as: "dashboard"  
  
  get "posts/index",        to: "posts#index",      as: "posts"
  get "posts/create",       to: "posts#create",     as: "create_posts"
  get '/posts/dashboard',    to: "posts#dashboard",   as: "dashboard_posts"  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/cliente.rb
class Cliente < ApplicationRecord
    has_many :departamento, dependent: :delete_all
    paginates_per 20

    def renta_total
        if self.departamento.present?
            rentas = []
            self.departamento.map do |r|
                if r.rent != nil
                    rentas << r.rent.to_i 
                end
            end 
            rentas
        else
            "Sin arriendo"             
        end
    end
    # def numero_asistentes
    #     asis =[]
    #     self.concerts.map do |c|
    #         asis << c.asistentes
    #     end
    #     asis
    # end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
    before_action :set_cliente, only: %i[ show edit update destroy] 
    before_action :authenticate_user!

    def index
        @clientes = Cliente.includes(:departamentos)
        @q = Cliente.ransack(params[:q])
        @clientes = @q.result(distinct:true).all.order(id: :asc).page(params[:page])
    end
    def show
    end
    def new
        @cliente = Cliente.new
        @cliente.departamentos.build
    end
    def edit
    end
    def create
        @cliente = Cliente.new(cliente_params)
        if @cliente.save
            redirect_to clientes_path
        else
            render :new
        end
    end
    def update
        if @cliente.update(cliente_params)
            redirect_to @cliente
        else
            render :edit
        end
    end
    def destroy
        @cliente.destroy
        redirect_to clientes_url
    end

    private
    def set_cliente
        @cliente = Cliente.find(params[:id])
    end
    def cliente_params
        params.require(:cliente).permit(:nombre, :apellido, :email, :telefono, departamentos_attributes:[:id, :numbre, :sale_price, :_destroy])
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/edit.html.erb
<h1>Esta es la vista para editar clientes</h1>
<div class="col-6">
    <%= form_with(model: @cliente) do |form|%>
        <div>
            <%= form.label :nombre %>
            <%= form.text_field :nombre, class: "form-control"  %>
        </div>
        <div>
            <%= form.label :apellido %>
            <%= form.text_field :apellido, class: "form-control"  %>
        </div>
        <div>
            <%= form.label :email %>
            <%= form.text_field :email, class: "form-control"  %>
        </div>
        <div>
            <%= form.label :telefono %>
            <%= form.text_field :telefono, class: "form-control"  %>
        </div>
        <div>
            <%= form.submit nil, class: "btn btn-secondary mt-5" %>
        </div>
    <% end %>
</div>
<%= link_to "Lista Clientes", clientes_path, class: "btn btn-secondary mt-5" %>

app/views/clientes/index.html.erb
<h1 class="mb-5 d-flex justify-content-center">Lista de clientes</h1>
<%# inicio buscador %>
    <div class="d-flex justify-content-end mb-5">
        <%= search_form_for @q do |f| %>
        <div class="d-flex mb-2 mb-lg-0 gap-3">
        <div class="">
            <%= f.search_field :nombre_or_apellido_or_email_cont, class: "form-control", placeholder: "¿Qué cliente buscas?" %>
        </div>
        <div class="">
        <%= f.submit "Search", class: "btn btn-outline-secondary" %> 
        </div>     
        </div>
        <% end %>
    </div>
<%# fin buscador %>
<h4>Total Rentas: $<%= @total_arriendos_deptos %></h4>
<table class="table table-bordered tabla" >
    <thead>
        <tr>
            <th>ID Cliente</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Email</th>
            <th>Teléfono</th>
            <th>Propiedades</th>
            <th>Renta Total</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        <% @clientes.each do |cliente| %>
            <tr>
                <td> <%= cliente.id %> </td>
                <td> <%= cliente.nombre %></td>
                <td> <%= cliente.apellido %></td>
                <td> <%= cliente.email %></td>
                <td> <%= cliente.telefono %></td>
                <td> <%= cliente.departamento.ids %></td>
                <td> $<%=  number_with_delimiter(cliente.renta_total.sum, :delimiter => '.') %></td>
                <td class="d-flex justify-content-evenly"><%= link_to cliente, class:"btn btn-secondary" do%>Ver <%end%>
                    <%= link_to "Editar", edit_cliente_path(cliente), class:"btn btn-secondary"%>
                    <%= button_to "Eliminar", cliente, method: :delete, data: {confirm: "Seguro?"}, class:"btn btn-danger" %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>
<div class="d-flex justify-content-end">  
<%= paginate @clientes, theme: 'bootstrap-5' %> 
<%# <%= paginate @books, theme: 'bootstrap-5' %> 
</div>
<div class="d-flex justify-content-evenly">
<%= link_to "Agregar cliente nuevo", new_cliente_path, class: "btn btn-secondary" %>
<%= link_to "Lista de clientes", clientes_path, class: "btn btn-secondary" %>
</div>
<%= link_to 'Volver', :back, class:"" %>

app/views/clientes/new.html.erb
<div>
    <h1>Esta es la vista para crear clientes</h1>
    <div class="col-6">
        <%= form_with(model: @cliente) do |form|%>
            <div>
                <%= form.label :nombre %>
                <%= form.text_field :nombre, class: "form-control"  %>
            </div>
            <div>
                <%= form.label :apellido %>
                <%= form.text_field :apellido, class: "form-control"  %>
            </div>
            <div>
                <%= form.label :email %>
                <%= form.text_field :email, class: "form-control"  %>
            </div>
            <div>
                <%= form.label :telefono %>
                <%= form.text_field :telefono, class: "form-control"  %>
            </div>
            <div>
                <%= form.submit nil, class: "btn btn-secondary mt-5" %>
            </div>
        <% end %>
    </div>
</div>
<%= link_to "Lista Clientes", clientes_path, class: "btn btn-secondary mt-5" %>

app/views/clientes/show.html.erb
<h1 class="d-flex justify-content-evenly">Cliente</h1>
<div class="container mt-5 d-flex justify-content-evenly">
  <div class="card tabla" style="width: 25rem;"> 
    <div class="card-body">
      <h5 class="card-title">Nombre: <%= @cliente.nombre%> <%=  @cliente.apellido%></h5>
      <h6 class="card-subtitle mb-2 text-muted">ID: <%= @cliente.id %></h6>
      <p class="card-text">Mail: <%= @cliente.email %></p>
      <p class="card-text">Teléfono: <%=  @cliente.telefono%></p>
      <p class="card-text">Propiedades: <%=  @cliente.departamento.ids%></p>
      <p class="card-text">Rentas: <%=  @cliente.renta_total%></p>
      <p class="card-text">Renta promedio: $<%=  number_with_delimiter(@cliente.renta_total.sum/@cliente.renta_total.length, :delimiter => '.')%></p>
      <p class="card-text">Renta Total: $<%=  number_with_delimiter(@cliente.renta_total.sum, :delimiter => '.')%></p>
      <div class="d-flex justify-content-evenly">
          <%= link_to 'Lista', clientes_path, class:"btn btn-secondary" %>
          <%= link_to "Editar", edit_cliente_url(@cliente), class:"btn btn-secondary"%>
          <%= link_to 'Nuevo', new_cliente_path, class:"btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>