config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'api/news'
  get 'api/:date1/:date2',    to: 'api#between_dates'
  resources :blogs
  get 'pages/index'
  get 'inicio/index'
  root 'inicio#index'

  # get 'edificios/index'
  get "edificios",       to: "edificios#index",   as: "list_edificios"
  get 'edificios/new',   to: "edificios#new",     as: "new_edificio"
  get "edificios/:id",   to: "edificios#show",     as: "edificio"
  get "edificios/:id/edit", to: "edificios#edit",  as: "edit_edificio"
  
  post "edificios",      to: "edificios#create"
  patch "edificios/:id", to: "edificios#update"
  put "edificios/:id",   to: "edificios#update" 
  delete "edificios/:id", to: "edificios#destroy",  as: "eliminar_edificio"   
  ###############################
  resources :departamentos
  #Por que agrega esto en la guía
  #################################
  get "clientes",          to: "clientes#index",   as: "clientes"
  get "clientes/new",      to: "clientes#new",     as: "new_cliente"
  get "clientes/:id",      to: "clientes#show",    as: "cliente"
  get "clientes/:id/edit", to: "clientes#edit",    as: "edit_cliente"

  post "clientes",         to: "clientes#create"
  patch "clientes/:id",     to: "clientes#update"
  put "clientes/:id",       to: "clientes#update"
  delete "clientes/:id",    to: "clientes#destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "pages/index",        to: "pages#index",      as: "pages"
  get "pages/create",       to: "pages#create",     as: "create_pages"
  get '/pages/dashboard',    to: "pages#dashboard",   as: "dashboard"  
  
  get "posts/index",        to: "posts#index",      as: "posts"
  get "posts/create",       to: "posts#create",     as: "create_posts"
  get '/posts/dashboard',    to: "posts#dashboard",   as: "dashboard_posts"  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/blog.rb
class Blog < ApplicationRecord
    paginates_per 20

    validates :title, presence: true
    validates :image_url, presence: true
    validates :content, presence: true
    validates :status, presence: true

    enum status: [:draft, :published]
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    #@blogs = Blog.all
    @q = Blog.ransack(params[:q]) 
    @blogs = @q.result(distinct:true).all.order(id: :asc).page(params[:page])
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :image_url, :content, :author, :status)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
<div class="container mt-5 d-flex justify-content-evenly mb-5">
    <div class="card tabla" style="width: 25rem;"> 
        <div class="card-body">
            <h5 class="card-title d-flex justify-content-center">Title: <%= blog.title %></h5>
            <h5 class="card-title d-flex justify-content-center">Author: <%= blog.author %></h5>
            <p class="card-text d-flex justify-content-evenly">Content: <%= blog.content %></p>
            <p class="card-text d-flex justify-content-evenly">Status: <%= blog.status %></p>
            <div>
            </div><img src="<%=blog.image_url %>" class="m-5"  alt="<%= blog.title %>" width="250" height="250">
            <div class="d-flex justify-content-evenly">
                <%= link_to 'Lista', blogs_path, class:"btn btn-secondary" %>
                <%= link_to 'Editar', edit_blog_path(blog), class:"btn btn-secondary" %>
                <%= link_to 'Nuevo', new_blog_path, class:"btn btn-secondary" %>
                <%= link_to "Eliminar", blog_path(blog), class:"btn btn-danger", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                    } %>
            </div>
        </div>
    </div>
</div>
</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="field mb-3">
    <%= form.label :title, style: "display: block", class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control', placeholder: 'Escribe tu post' %>
  </div>

  <div class="field mb-3">
    <%= form.label :image_url, style: "display: block", class: 'form-label' %>
    <%= form.text_field :image_url, class: 'form-control', placeholder: 'Escribe tu post' %>
  </div>

  <div class="field mb-3">
    <%= form.label :content, style: "display: block", class: 'form-label' %>
    <%= form.text_area :content, class: 'form-control', placeholder: 'Escribe tu post' %>
  </div>

  <div class="field mb-3">
    <%= form.label :author, style: "display: block", class: 'form-label' %>
    <%= form.text_field :author, class: 'form-control', placeholder: 'Escribe tu post' %>
  </div>

  <div class="field mb-3">
    <%= form.label :status, style: "display: block", class: 'form-label' %>
    <%= form.select(:status, Blog.statuses.keys.map{|b| [b.humanize, b]}, {}, {class: 'form-control'}) %>

  </div>

  <div>
    <%# <%= form.submit %>
    <button type="submit" class="btn btn-secondary">Guardar</button> 
    <%= link_to "Blog", root_path, class:"btn btn-secondary" %> 
  </div>
<% end %>
</div>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Show this blog", @blog %> |
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/index.html.erb
<p style="color: green"><%= notice %></p>
<div class ="container">
<% flash.each do |type, msg| %>
    <div class="alert alert-info">
        <%= msg %>
    </div>
<% end %>

<h1 class="m-5 d-flex justify-content-center">Nuestros Posts</h1>
<%# inicio buscador %>
  <div class="d-flex justify-content-end">
    <%= search_form_for @q do |f| %>
    <div class="d-flex mb-2 mb-lg-0 gap-3">
      <div class="">
        <%= f.search_field :title_or_content_or_author_cont, class: "form-control", placeholder: "¿Que buscas?" %>
      </div>
      <div class="">
        <%= f.select :status_eq, options_for_select(Blog.statuses ,
        @q.status_eq), {include_blank: "Ver todos"},{class: "form-control"} %> 
      </div>
      <div class="">
      <%= f.submit "Search", class: "btn btn-outline-secondary" %> 
      </div>     
    </div>
    <% end %>
  </div>
<%# fin buscador %>
<%= link_to "Crear nuevo blog", new_blog_path, class:"btn btn-secondary mb-2" %>
    <table class="table table-striped tabla">
    <thead>
        <tr>
        <th scope="col">#</th>
        
        <th scope="col">Title </th>
        <th scope="col">Content</th>
        <th scope="col">Image url</th>
        <th scope="col">Created at</th>
        <th scope="col">Status</th>
        <th scope="col">Author</th>
        <th scope="col">Acciones</th>
        </tr>
    </thead>
    <tbody>
    <% @blogs.each do |blog| %>
        <tr>
          <th scope="row"><%= blog.id %></th>
          <td><%= blog.title %></td>
          <td><%= blog.content %></td>
          <td> <img src="<%=blog.image_url %>" alt="<%= blog.title %>" width="50" height="50"></td>        
          <td><%= blog.created_at %></td>
          <td><%= blog.status %></td>
          <td><%= blog.author %></td>
          <td class="d-flex justify-content-evenly">
              <%= link_to "Ver", blog_path(blog), class:"btn btn-secondary"%> 
              <%= link_to "Editar", edit_blog_path(blog), class:"btn btn-secondary"%> 
              <%= link_to "Eliminar", blog_path(blog), class:"btn btn-danger", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                    } %>
          </td> 
        </tr>
    <% end %>
    </tbody>
    
  </table>
  <div class="d-flex justify-content-end">  
    <%= paginate @blogs, theme: 'bootstrap-5'  %>
    <%# <%= paginate @books, theme: 'bootstrap-5' %> 
  </div>
</div>

<%= link_to "Blog", blogs_path, class:"btn btn_secondary" %>

<!-- app/views/posts/index.html.erb -->
<p id="notice"><%= notice %></p>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blog %>

<div>
  <%= link_to "Edit this blog", edit_blog_path(@blog) %> |
  <%= link_to "Back to blogs", blogs_path %>

  <%= button_to "Destroy this blog", @blog, method: :delete %>
</div>