config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'api/news'
  get 'api/:date1/:date2',    to: 'api#between_dates'
  resources :blogs
  get 'pages/index'
  get 'inicio/index'
  root 'inicio#index'

  # get 'edificios/index'
  get "edificios",       to: "edificios#index",   as: "list_edificios"
  get 'edificios/new',   to: "edificios#new",     as: "new_edificio"
  get "edificios/:id",   to: "edificios#show",     as: "edificio"
  get "edificios/:id/edit", to: "edificios#edit",  as: "edit_edificio"
  
  post "edificios",      to: "edificios#create"
  patch "edificios/:id", to: "edificios#update"
  put "edificios/:id",   to: "edificios#update" 
  delete "edificios/:id", to: "edificios#destroy",  as: "eliminar_edificio"   
  ###############################
  resources :departamentos
  #Por que agrega esto en la guía
  #################################
  get "clientes",          to: "clientes#index",   as: "clientes"
  get "clientes/new",      to: "clientes#new",     as: "new_cliente"
  get "clientes/:id",      to: "clientes#show",    as: "cliente"
  get "clientes/:id/edit", to: "clientes#edit",    as: "edit_cliente"

  post "clientes",         to: "clientes#create"
  patch "clientes/:id",     to: "clientes#update"
  put "clientes/:id",       to: "clientes#update"
  delete "clientes/:id",    to: "clientes#destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "pages/index",        to: "pages#index",      as: "pages"
  get "pages/create",       to: "pages#create",     as: "create_pages"
  get '/pages/dashboard',    to: "pages#dashboard",   as: "dashboard"  
  
  get "posts/index",        to: "posts#index",      as: "posts"
  get "posts/create",       to: "posts#create",     as: "create_posts"
  get '/posts/dashboard',    to: "posts#dashboard",   as: "dashboard_posts"  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/edificio.rb
class Edificio < ApplicationRecord
    has_many :departamentos, dependent: :delete_all
    #aqui sabe cual es el nombre de la clave foranea
    #al modelo en plural en que clase y tabla
    validates :nombre, presence: true
    validates :direccion, presence: true
    validates :ciudad, presence: true
    accepts_nested_attributes_for :departamentos,
                                    allow_destroy: true,
                                    reject_if: proc { |attributes| attributes['numero'].blank?}

    paginates_per 20
    # validaciones para que no se guarde el objeto vacío
    #def Departamento
    #    Departamento.where(edificio_id: self.id)
    #end
    def total_arriendo_edificio
        if self.departamentos.present?
            rentas = []
            self.departamentos.map do |r|
                if r.rent != nil
                    rentas << r.rent.to_i 
                end
            end 
            rentas.sum
        else
            "Sin arriendo"             
        end
    end
    def nombre_completo
        "#{id} #{"-"} #{nombre}"
      end
end

app/controllers/edificios_controller.rb
class EdificiosController < ApplicationController
    before_action :set_edificio, only: %i[ show edit update destroy ]
    before_action :authenticate_user!
    # %i evita usar ; y :
    def index
        #@edificios = Edificio.all.order(created_at: :asc)
        #El método index del controlador disponibiliza por medio
        #de la variable de instancia @edificios, la lista de edificio disponible
        #@edificios = Edificio.order(created_at: :asc).all.page(params[:page])
        @edificios = Edificio.includes(:departamentos)
        @q = Edificio.ransack(params[:q])
        @edificios = @q.result(distinct:true).all.order(id: :asc).page(params[:page])
    end
    def show
    end
    def new
        @edificio = Edificio.new
        #para el formulario anidado:
        @edificio.departamentos.build
    end
    def edit
    end
    def create
        @edificio = Edificio.new(edificio_params)
        # params son permisos para guardar la información
        if @edificio.save
            redirect_to list_edificios_path, notice: "Edificio Creado Exitosamente."
        else
            render :new, status: :unprocessable_entity        
        end
    end
    def update
        if @edificio.update(edificio_params)
            redirect_to @edificio, notice: "Edificio actualizado Exitosamente."
        else
            render :edit, status: :unprocessable_entity        
        end
    end
    def destroy
        @edificio.destroy
        redirect_to edificios_url, notice: "Edificio eliminado exitosamente"
    end

    private

    def set_edificio
        @edificio = Edificio.find(params[:id])
    end
    def edificio_params
        #params.require(:edificio).permit(:nombre, :direccion, :ciudad)
        #para los formularios anidados:
        params.require(:edificio).permit(:nombre, :direccion, :ciudad, departamentos_attributes:[:id, :numbre, :sale_price, :_destroy])
    end
end

app/helpers/edificios_helper.rb
module EdificiosHelper
end

app/views/edificios/edit.html.erb
<div>
    <h1>Editar Edificio</h1>
<div class="col-6">
    <%= form_with(model: @edificio) do |form| %>
        <% if @edificio.errors.any? %>
                <div id="error_explanation">
                <h2><%= pluralize(@edificio.errors.count, "error") %> prohibited this building from being saved:</h2>
                <ul>
                    <% @edificio.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                    <% end %>
                </ul>
                </div>
            <% end %>
        <div>
            <%= form.label :nombre %>
            <%= form.text_field :nombre, class: "form-control" %>
            <%# no usar form_for %>
        </div>
        <div>
            <%= form.label :direccion %>
            <%= form.text_field :direccion, class: "form-control" %>
        </div>
        <div>
            <%= form.label :ciudad %>
            <%= form.text_field :ciudad, class: "form-control" %>
        </div>
        <div>
            <%# <%= form.submit "Guardar" %>
            <%= form.submit nil, class: "btn btn-secondary mt-5" %>
        </div>
    <% end %>
    </div>
</div>
<%= link_to "Lista de edificios", list_edificios_path, class: "btn btn-secondary mt-5" %>

app/views/edificios/index.html.erb
<h1 class="mb-5 d-flex justify-content-center">Lista de edificios</h1>
<%# inicio buscador %>
    <div class="d-flex justify-content-end mb-5">
        <%= search_form_for @q do |f| %>
        <div class="d-flex mb-2 mb-lg-0 gap-3">
        <div class="">
            <%= f.search_field :nombre_or_direccion_or_ciudad_cont, class: "form-control", placeholder: "¿Qué buscas?" %>
        </div>
        <div class="">
        <%= f.submit "Search", class: "btn btn-outline-secondary" %> 
        </div>     
        </div>
        <% end %>
    </div>
<%# fin buscador %>
<table class="table table-bordered tabla" >
    <thead>
        <tr>
            <th>Id Edificio</th>
            <th>Nombre</th>
            <th>Dirección</th>
            <th>Ciudad</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        <% @edificios.each do |edificio| %>
            <tr>
                <td><%= edificio.id %></td>
                <td><%= edificio.nombre %></td>
                <td><%= edificio.direccion %></td>
                <td><%= edificio.ciudad %></td>
                <td class="d-flex justify-content-evenly"><%= link_to edificio, class:"btn btn-secondary" do%>Ver <%end%>
                    <%= link_to "Editar", edit_edificio_path(edificio), class:"btn btn-secondary"%>
                    <%= button_to "Eliminar", edificio, method: :delete, data: {confirm: "Seguro?"}, class:"btn btn-danger" %>
                <%# link_to "show", edificio, class:"btn btn-primary" %> 
                <%# <%= link_to "Eliminar", edificio, data: {turbo_method: :delete}, class:"btn btn-danger" %> 
                </td>
            </tr>
        <% end %>
    </tbody>
</table>
<div class="d-flex justify-content-end">  
<%= paginate @edificios, theme: 'bootstrap-5' %> 
<%# <%= paginate @books, theme: 'bootstrap-5' %> 
</div>
<div class="d-flex justify-content-evenly">
<%= link_to "Crear edificio nuevo", new_edificio_path, class: "btn btn-secondary" %>
<%= link_to "Lista de departamentos", departamentos_path, class: "btn btn-secondary" %>
</div>
<%= link_to 'Volver', :back, class:"" %>

app/views/edificios/new.html.erb
<div>
    <h1>Crear Edificios</h1>
    <div class="col-6">
        <%= form_with(model: @edificio) do |form| %>
            <% if @edificio.errors.any? %>
                    <div id="error_explanation">
                    <h2><%= pluralize(@edificio.errors.count, "error") %> No se puede crear el edificio:</h2>
                    <ul>
                        <% @edificio.errors.each do |error| %>
                        <li><%= error.full_message %></li>
                        <% end %>
                    </ul>
                    </div>
                <% end %>
            <div>
                <%= form.label :nombre %>
                <%= form.text_field :nombre, class: "form-control" %>
                <%# no usar form_for %>
            </div>
            <div>
                <%= form.label :direccion %>
                <%= form.text_field :direccion, class: "form-control" %>
            </div>
            <div>
                <%= form.label :ciudad %>
                <%= form.text_field :ciudad, class: "form-control" %>
            </div>
            <%# <p>Apartment fields</p>
            <%= form.fields_for :departamentos do |departamento_form| %>
                <%# <%= departamento_form.label :numero %>
                <%# <%= departamento_form.text_field :numero %>
                <%# <%= departamento_form.label :rent %>
                <%# <%= departamento_form.text_field :rent %>
            <%# <% end %>
            <div>
                <%# <%= form.submit "Guardar" %>
                <%= form.submit nil, class: "btn btn-secondary mt-5" %>
            </div>
        <% end %>
    </div>
</div>
<%= link_to "Lista Edificios", edificios_path, class: "btn btn-secondary mt-5" %>

app/views/edificios/show.html.erb
<div class="container mt-5 d-flex justify-content-evenly mb-5">
    <div class="card tabla" style="width: 25rem;"> 
        <div class="card-body">
            <h5 class="card-title">Edificio: <%= @edificio.nombre %></h5>
            <h6 class="card-subtitle mb-2 text-muted">ID: <%= @edificio.id %></h6>
            <p class="card-text">Dirección: <%= @edificio.direccion %></p>
            <p class="card-text">Ciudad: <%=  @edificio.ciudad%></p>
            <div>
                <%= link_to 'Lista', list_edificios_path, class:"btn btn-secondary" %>
                <%= link_to 'Editar', edit_edificio_path(@edificio), class:"btn btn-secondary" %>
                <%= link_to 'Nuevo', new_edificio_path, class:"btn btn-secondary" %>
            </div>
        </div>
    </div>
</div>
<h3 class="d-flex justify-content-evenly">Departamentos</h3>
<table class= "table table-bordered tabla">
    <thead>
        <tr>
            <th>Número</th>
            <th>Renta</th>
        </tr>
    </thead>
    <tbody>
        <% @edificio.departamentos.each do |depto| %>
            <tr>
                <td><%= depto.numero %></td>
                <td>$<%= number_with_delimiter(depto.rent, :delimiter => '.')%></td>
            </tr>
            
        <% end %>
        <tr>
            <td>Total:</td>
            <td>$<%=  number_with_delimiter(@edificio.total_arriendo_edificio, :delimiter => '.')%></td> 
        </tr>
    </tbody>
</table>