config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'api/news'
  get 'api/:date1/:date2',    to: 'api#between_dates'
  resources :blogs
  get 'pages/index'
  get 'inicio/index'
  root 'inicio#index'

  # get 'edificios/index'
  get "edificios",       to: "edificios#index",   as: "list_edificios"
  get 'edificios/new',   to: "edificios#new",     as: "new_edificio"
  get "edificios/:id",   to: "edificios#show",     as: "edificio"
  get "edificios/:id/edit", to: "edificios#edit",  as: "edit_edificio"
  
  post "edificios",      to: "edificios#create"
  patch "edificios/:id", to: "edificios#update"
  put "edificios/:id",   to: "edificios#update" 
  delete "edificios/:id", to: "edificios#destroy",  as: "eliminar_edificio"   
  ###############################
  resources :departamentos
  #Por que agrega esto en la guía
  #################################
  get "clientes",          to: "clientes#index",   as: "clientes"
  get "clientes/new",      to: "clientes#new",     as: "new_cliente"
  get "clientes/:id",      to: "clientes#show",    as: "cliente"
  get "clientes/:id/edit", to: "clientes#edit",    as: "edit_cliente"

  post "clientes",         to: "clientes#create"
  patch "clientes/:id",     to: "clientes#update"
  put "clientes/:id",       to: "clientes#update"
  delete "clientes/:id",    to: "clientes#destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "pages/index",        to: "pages#index",      as: "pages"
  get "pages/create",       to: "pages#create",     as: "create_pages"
  get '/pages/dashboard',    to: "pages#dashboard",   as: "dashboard"  
  
  get "posts/index",        to: "posts#index",      as: "posts"
  get "posts/create",       to: "posts#create",     as: "create_posts"
  get '/posts/dashboard',    to: "posts#dashboard",   as: "dashboard_posts"  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Edificios</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# icono %>
    <!-- https://www.svgrepo.com/svg/202946/web-design -->
    <%# <link rel="shortcut icon" href="/assets/city-view-svgrepo-com.svg" type="image/x-icon"> %>
    <link rel="shortcut icon" href="https://www.svgrepo.com/show/83118/city-view.svg" type="image/x-icon">
    <!-- CSS only bootstrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">    
    <%# fin bootstrap %>
    <!-- iconos font awesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />  
    <%# fin font awesome %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg bg-light mb-5">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="https://www.svgrepo.com/show/83118/city-view.svg" alt="" width="30" height="24" class="d-inline-block align-text-top">
          <%= link_to "DEPTOS", root_path, class:"navbar-brand nav-link active" %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li><% if user_signed_in? %>
            <p class="mt-2"><%= current_user.email %></p>
          <% end %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="dropdown-toggle nav-link" data-bs-toggle="dropdown" role="button" aria-haspopup="true">
              <i class="fa-solid fa-circle-user" style="font-size:24px"></i>
              <span class="caret"></span>
            </a>
          
          <% if current_user %>
            <ul class="dropdown-menu">
              <li><%= link_to 'Crear Departamento', new_departamento_path, class:"dropdown-item" %> </li>
              <li><%= link_to 'Crear Edificio', new_edificio_path, class:"dropdown-item" %> </li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Mi perfil', edit_user_registration_path, class:"dropdown-item" %> </li>
              <li role="separator" class="divider"></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to 'Sign Out', destroy_user_session_path, class:"dropdown-item", data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %></li>
            </ul>
          </li> 
          <% else %>
           <ul class="dropdown-menu">
            <li><%= link_to 'Registar', new_user_registration_path, class:"dropdown-item" %></li>
            <li><%= link_to 'Log in', new_user_session_path, class:"dropdown-item" %></li>
          </ul>
          <% end %>
        <li class="nav-item">
          <% if current_user %>
            <%= link_to "Log Out", destroy_user_session_path, class:"nav-link active" , data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
          <% else %>
            <%= link_to 'Log In', new_user_session_path, class:"nav-link active" %>
          <% end %>  
        </li>
        <li class="nav-item">
          <%= link_to "Inicio", root_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Clientes", clientes_path, class:"nav-link active" %>
        </li><li class="nav-item">
          <%= link_to "Blog", blogs_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Departamentos", departamentos_path, class:"nav-link active" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Edificios</a>
          <ul class="dropdown-menu">
            <% @edificios.each do |edificio| %>  
              <li>
                <a class="dropdown-item" href="/edificios/<%= edificio.id %>"><%= edificio.nombre %></a>
              </li>
            <% end %> 
            <li><hr class="dropdown-divider"></li> 
            <li>
              <%= link_to "Lista de los edificios", list_edificios_path, class: "dropdown-item"%>
            </li>
            <li><hr class="dropdown-divider"></li>
            <li>
              <%# <a class="dropdown-item" href="#">Something else here</a> %>
              <%= link_to "Crear edificio nuevo", new_edificio_path, class: "dropdown-item" %>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Administración</a>
        </li>
      </ul>
      <%# <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Buscar</button>
      </form> %>
    </div>
  </div>
</nav>
  <div class= container>
  <%# inicio mensaje %>
    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
          <%= msg %>
        </div>
      <% end %>
  <%# fin mensaje %>
    <%= yield %>
  </div>  
  <!-- JavaScript Bundle with Popper desde bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
    <%# fin bootstrap %>
    <footer class="bg-light mt-5 container-fluid text-center p-4">
      <%# <p class="">DEPTOS </p> %>
      <h6 class="m-4 pb-3">© <%= Time.now.year %> <a href="https://mariajosevillasante.github.io/mi_pagina/">María José Villasante</a> para DEPTOS Latam. Todos los derechos reservados.</h6>
    </footer>
  </body>

  
</html>